# Generated by Django 4.2.7 on 2025-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_searchquery_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={},
        ),
        migrations.RenameField(
            model_name='clothingitem',
            old_name='scraped_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='material',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='user',
        ),
        migrations.AddField(
            model_name='searchquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='source_website',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
    ]
