# Generated by Django 4.2.7 on 2025-04-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_clothingitem_options_alter_searchquery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ClothingItem',
        ),
        migrations.DeleteModel(
            name='SearchQuery',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
